apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailserver
  namespace: dev-mailserver
  labels:
    app: mailserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailserver
  template:
    metadata:
      labels:
        app: mailserver
    spec:
      containers:
      - name: mailpit
        image: axllent/mailpit:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: smtp
          containerPort: 1025
          protocol: TCP
        - name: http-ui
          containerPort: 8025
          protocol: TCP
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
