apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: github-build-deploy-run-
  namespace: tekton-build
spec:
  pipelineRef:
    name: github-build-deploy-pipeline
  workspaces:
    - name: shared-source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
