---
# 8. Keycloak Instance (CRD handled by operator)
apiVersion: k8s.keycloak.org/v2beta1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgres-db
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
  http:
    tlsSecret: "keycloak-tls-secret"
    httpEnabled: true
    proxy:
      headers: xforwarded
  hostname:
    strict: false    
  ingress:
    enabled: true
